### ISSUE TITLE
Quote filtering

### ISSUE THREAD

**Issue by mikaelssen** [mikaelssen/FruitBowlBot#9]
Gotta add a way to filter existing quotes, people keeps quoting the bot's "thanks" ...

**Comment by DrVirite** [comment]
Worth reading: https://www.dotnetperls.com/levenshtein

**Comment by mikaelssen** [comment]
I can see where that would fit, but i'd rather use 100% equal quotes, as some people make typos and then send inn a new one just after the wrong one, thus derping it if it's like 1 or 3 letter differences, or 20% if we use %. 
Will look into getting this done tomorrow or so though :)

**Comment by mikaelssen** [comment]
Started on this, it currently downloads the quotes from the website, and loads them into a list, not added any Filtering yet, don't have that much time on my hands today it seems.
